### ISSUE TITLE
ng build - issues

### ISSUE THREAD

**Issue by MrTiptop** [mariolukas/HydraPlay#30]
Hello, firstly - KUDOS man!!!! Great work here. So i am completely new to angular here so please let me apologise now.. I have issue when running `ng build`

root@DietPi:~/HydraPlay/hydraplay# ng build
Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/root/HydraPlay/hydraplay/node_modules/@angular-devkit/core/src/workspace/workspace.js:215:42)
    at MergeMapSubscriber._tryNext (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/operators/switchMap.js:86:26)
    at InnerSubscriber._next (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/Subscriber.js:67:18)
    at /root/HydraPlay/hydraplay/node_modules/rxjs/internal/util/subscribeTo.js:17:28
    at Object.subscribeToResult (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/operators/switchMap.js:65:54)
    at SwitchMapSubscriber._next (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/operators/switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/operators/switchMap.js:86:26)
    at InnerSubscriber._next (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/Subscriber.js:67:18)
    at /root/HydraPlay/hydraplay/node_modules/rxjs/internal/util/subscribeTo.js:17:28
    at Object.subscribeToResult (/root/HydraPlay/hydraplay/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)

**Comment by mariolukas** [comment]
New version solved this.
